Лабораторна Робота №1
Виконав Чемоданов Iлля Миколайович (Фiт 4-5)
Варiант 23

In [8]:
import numpy as np

1. Створіть одновимірний масив (вектор) зі значеннями квадратних коренів з кожного натурального числа, починаючи з 1, та виведіть його значення. 

In [9]:
n = 10  # Кількість значень, які ви хочете створити
vector = np.sqrt(np.arange(1, n+1))
print(vector)


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями залишків від ділення кожного числа на 3, починаючи з 1, та виведіть його значення. 

In [11]:
matrix = np.arange(1, 10).reshape(3, 3) % 3 
print(matrix)

[[1 2 0]
 [1 2 0]
 [1 2 0]]


3.Створіть масив розміром 9x9, заповніть його випадковими натуральними числами від 1 до 50 та знайдіть відсоток чисел, які діляться на 3 без остачі. 

In [13]:
matrix = np.random.randint(1, 51, size=(9, 9))
divisible_by_3 = matrix % 3 == 0
percentage = (np.count_nonzero(divisible_by_3) / matrix.size) * 100

print("Матриця:")
print(matrix)
print(f"Відсоток чисел, які діляться на 3 без остачі: {percentage}%")



Матриця:
[[12 43 19 19 14  5 47 23 10]
 [23  2  1 12 29 25  9 48 16]
 [ 8 27 50 21  6 10 40  6 40]
 [33  1 35 35 42 33 12 45 49]
 [20 39 30 44 14  8 39 40 26]
 [34 32 42 23  5 19 16 13  4]
 [17 16  4  7 24 39 22  1 30]
 [11 34 15  2  4 11 28 37 20]
 [ 6  3 27  5  5 16 26 43 10]]
Відсоток чисел, які діляться на 3 без остачі: 29.629629629629626%


4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.9 до 0.9 та виведіть його значення. 


In [14]:
matrix = np.random.uniform(-0.9, 0.9, size=(4, 4))
print(matrix)

[[ 0.15515646 -0.57539147 -0.85647017  0.06790354]
 [ 0.88559878  0.25265637  0.72014367  0.21856685]
 [ 0.47204755 -0.06060185  0.64239306 -0.6525066 ]
 [-0.84832909 -0.06860187  0.74741115  0.67590282]]


5.Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та виконайте на них поелементні операції додавання, віднімання та множення. 

In [15]:
np.random.seed(0)  # Це для того, щоб результат був відтворюваним
array1 = np.random.randint(1, 6, size=7)
array2 = np.random.randint(1, 6, size=7)

#Додавання
result_add = array1 + array2

#Вiднiмання
result_subtract = array1 - array2

#Множення
result_multiply = array1 * array2

print("Перший масив:", array1)
print("Другий масив:", array2)
print("Результат додавання:", result_add)
print("Результат віднімання:", result_subtract)
print("Результат множення:", result_multiply)




Перший масив: [5 1 4 4 4 2 4]
Другий масив: [3 5 1 1 5 3 2]
Результат додавання: [8 6 5 5 9 5 6]
Результат віднімання: [ 2 -4  3  3 -1 -1  2]
Результат множення: [15  5  4  4 20  6  8]


6.Створіть два вектори розміром 4, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток. 

In [16]:
vector1 = np.array([1.5, 2.0, 3.5, 4.2])
vector2 = np.array([0.5, 1.0, 2.5, 3.0])

#Обчислення
scalar_product = np.dot(vector1, vector2)

print("Перший вектор:", vector1)
print("Другий вектор:", vector2)
print("Скалярний добуток:", scalar_product)


Перший вектор: [1.5 2.  3.5 4.2]
Другий вектор: [0.5 1.  2.5 3. ]
Скалярний добуток: 24.1


7.Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 15 та перемножте їх між собою. 

In [17]:
np.random.seed(0)  # Це для того, щоб результат був відтворюваним
matrix1 = np.random.randint(1, 16, size=(2, 3))
matrix2 = np.random.randint(1, 16, size=(3, 4))

#Перемноження матриць
result_matrix = np.dot(matrix1, matrix2)
# Або використовуйте оператор @:
# result_matrix = matrix1 @ matrix2

print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)
print("Результат множення:")
print(result_matrix)


Перша матриця:
[[13  6  1]
 [ 4 12  4]]
Друга матриця:
[[ 8 10  4  6]
 [ 3  5  8  7]
 [ 9  9 13 11]]
Результат множення:
[[131 169 113 131]
 [104 136 164 152]]


8.Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю. 

In [18]:
np.random.seed(0)  # Це для того, щоб результат був відтворюваним
matrix = np.random.randint(1, 16, size=(2, 2))

#Знаходимо обернену матрицю
inverse_matrix = np.linalg.inv(matrix)

print("Початкова матриця:")
print(matrix)
print("Обернена матриця:")
print(inverse_matrix)


Початкова матриця:
[[13  6]
 [ 1  4]]
Обернена матриця:
[[ 0.08695652 -0.13043478]
 [-0.02173913  0.2826087 ]]


9.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 3 до 15 та транспонуйте її. 


In [19]:
np.random.seed(0)  # Це для того, щоб результат був відтворюваним
matrix = np.random.randint(3, 16, size=(3, 3))

#Транспонтуемо матрицю
transposed_matrix = matrix.T

print("Початкова матриця:")
print(matrix)
print("Транспонована матриця:")
print(transposed_matrix)


Початкова матриця:
[[15  8  3]
 [ 6 14  6]
 [10 12  6]]
Транспонована матриця:
[[15  6 10]
 [ 8 14 12]
 [ 3  6  6]]


10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму добутків елементів кожного стовпця матриці на відповідний елемент вектору. 

In [20]:
np.random.seed(0)  # Це для того, щоб результат був відтворюваним
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)

result = np.sum(matrix * vector, axis=0)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Результат:")
print(result)


Матриця:
[[ 6  1  4  4]
 [ 8 10  4  6]
 [ 3  5  8  7]]
Вектор:
[9 9 2 7]
Результат:
[153 144  32 119]


11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток вектора на матрицю. 

In [22]:

# Створіть матрицю розміром 2x3
matrix = np.random.rand(2, 3)

# Створіть вектор розміром 3
vector = np.random.rand(3)

# Обчисліть добуток матриці на вектор
result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Результат:")
print(result)

Матриця:
[[0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]]
Вектор:
[0.0871293  0.0202184  0.83261985]
Результат:
[0.48978481 0.12735344]


12.Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток всіх елементів першої матриці. 

In [23]:
# Створюемо першу матрицю розміром 8x8 і заповнюемо її випадковими цілими числами в діапазоні від 1 до 10.
matrix1 = np.random.randint(1, 11, size=(8, 8))

# Обчислюемо добуток всіх елементів першої матриці за допомогою функції np.prod.
product = np.prod(matrix1)

# Виведимо першу матрицю та результат.
print("Перша матриця:")
print(matrix1)
print("Добуток всіх елементів першої матриці:", product)

Перша матриця:
[[ 1  3  4  9  2  4  4  4]
 [ 8  1  2 10 10  1  5  8]
 [ 4  3  8  3  1  1  5  6]
 [ 6  7  9  5  2  5 10  9]
 [ 2  2  8 10 10  4  7  8]
 [ 3  1  4  6 10  5  5  7]
 [ 5  5  4  5  5  9  5  4]
 [ 8  6  6  1  2  6 10  4]]
Добуток всіх елементів першої матриці: 0


13.Створіть дві матриці розміром 7x7, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть різницю їх елементів. 

In [24]:
# Створюемо дві матриці розміром 7x7 та заповнюемо їх випадковими дійсними числами від -1 до 1.
np.random.seed(0)  # Це для того, щоб результат був відтворюваним
matrix1 = np.random.uniform(-1, 1, size=(7, 7))
matrix2 = np.random.uniform(-1, 1, size=(7, 7))

# Знаходимо різницю елементів матриць.
difference_matrix = matrix1 - matrix2

# Виведимо матриці та результат.
print("Перша матриця:")
print(matrix1)
print("Друга матриця:")
print(matrix2)
print("Різниця елементів матриць:")
print(difference_matrix)

Перша матриця:
[[ 0.09762701  0.43037873  0.20552675  0.08976637 -0.1526904   0.29178823
  -0.12482558]
 [ 0.783546    0.92732552 -0.23311696  0.58345008  0.05778984  0.13608912
   0.85119328]
 [-0.85792788 -0.8257414  -0.95956321  0.66523969  0.5563135   0.7400243
   0.95723668]
 [ 0.59831713 -0.07704128  0.56105835 -0.76345115  0.27984204 -0.71329343
   0.88933783]
 [ 0.04369664 -0.17067612 -0.47088878  0.54846738 -0.08769934  0.1368679
  -0.9624204 ]
 [ 0.23527099  0.22419145  0.23386799  0.88749616  0.3636406  -0.2809842
  -0.12593609]
 [ 0.39526239 -0.87954906  0.33353343  0.34127574 -0.57923488 -0.7421474
  -0.3691433 ]]
Друга матриця:
[[-0.27257846  0.14039354 -0.12279697  0.97674768 -0.79591038 -0.58224649
  -0.67738096]
 [ 0.30621665 -0.49341679 -0.06737845 -0.51114882 -0.68206083 -0.77924972
   0.31265918]
 [-0.7236341  -0.60683528 -0.26254966  0.64198646 -0.80579745  0.67588981
  -0.80780318]
 [ 0.95291893 -0.0626976   0.95352218  0.20969104  0.47852716 -0.92162442
  -0.4343

14.Створіть матрицю розміром 9x9, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть суму елементів на головній діагоналі. 

In [25]:
# Створюемо матрицю розміром 9x9 та заповнюемо її випадковими дійсними числами від -10 до 10.
np.random.seed(0)  # Це для того, щоб результат був відтворюваним
matrix = np.random.uniform(-10, 10, size=(9, 9))

# Знаходимо суму елементів на головній діагоналі за допомогою функції np.trace.
sum_diagonal = np.trace(matrix)

# Виведимо матрицю та суму елементів на головній діагоналі.
print("Матриця:")
print(matrix)
print("Сума елементів на головній діагоналі:", sum_diagonal)

Матриця:
[[ 0.97627008  4.30378733  2.05526752  0.89766366 -1.52690401  2.91788226
  -1.24825577  7.83546002  9.27325521]
 [-2.33116962  5.83450076  0.5778984   1.36089122  8.51193277 -8.57927884
  -8.25741401 -9.59563205  6.65239691]
 [ 5.56313502  7.40024296  9.57236684  5.98317128 -0.77041275  5.61058353
  -7.63451148  2.79842043 -7.13293425]
 [ 8.89337834  0.43696644 -1.7067612  -4.70888776  5.48467379 -0.87699336
   1.36867898 -9.62420399  2.35270994]
 [ 2.24191445  2.33867994  8.87496157  3.63640598 -2.80984199 -1.25936092
   3.95262392 -8.79549057  3.33533431]
 [ 3.41275739 -5.79234878 -7.42147405 -3.69143298 -2.72578458  1.40393541
  -1.22796973  9.76747676 -7.95910379]
 [-5.82246488 -6.77380964  3.06216651 -4.93416795 -0.67378454 -5.11148816
  -6.82060833 -7.79249718  3.12659179]
 [-7.23634097 -6.06835277 -2.62549659  6.4198646  -8.05797448  6.75889815
  -8.07803184  9.5291893  -0.62697597]
 [ 9.53522176  2.09691039  4.78527159 -9.21624415 -4.34386075 -7.59606878
  -4.07719605

15.Створіть матрицю розміром 9x9, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця матриці. 

In [26]:
# Створюемо матрицю розміром 9x9 та заповнюемо її випадковими дійсними числами від -0.5 до 0.5.
np.random.seed(0)  # Це для того, щоб результат був відтворюваним
matrix = np.random.uniform(-0.5, 0.5, size=(9, 9))

# Знаходимо суму елементів кожного стовпця матриці за допомогою функції np.sum і параметру axis=0.
column_sum = np.sum(matrix, axis=0)

# Перетворюемо результат вектор-стовпчик за допомогою .reshape.
column_sum_vector = column_sum.reshape(-1, 1)

# Виводимо матрицю та вектор-стовпчик сум.
print("Матриця:")
print(matrix)
print("Вектор-стовпчик сум:")
print(column_sum_vector)

Матриця:
[[ 0.0488135   0.21518937  0.10276338  0.04488318 -0.0763452   0.14589411
  -0.06241279  0.391773    0.46366276]
 [-0.11655848  0.29172504  0.02889492  0.06804456  0.42559664 -0.42896394
  -0.4128707  -0.4797816   0.33261985]
 [ 0.27815675  0.37001215  0.47861834  0.29915856 -0.03852064  0.28052918
  -0.38172557  0.13992102 -0.35664671]
 [ 0.44466892  0.02184832 -0.08533806 -0.23544439  0.27423369 -0.04384967
   0.06843395 -0.4812102   0.1176355 ]
 [ 0.11209572  0.116934    0.44374808  0.1818203  -0.1404921  -0.06296805
   0.1976312  -0.43977453  0.16676672]
 [ 0.17063787 -0.28961744 -0.3710737  -0.18457165 -0.13628923  0.07019677
  -0.06139849  0.48837384 -0.39795519]
 [-0.29112324 -0.33869048  0.15310833 -0.2467084  -0.03368923 -0.25557441
  -0.34103042 -0.38962486  0.15632959]
 [-0.36181705 -0.30341764 -0.13127483  0.32099323 -0.40289872  0.33794491
  -0.40390159  0.47645947 -0.0313488 ]
 [ 0.47676109  0.10484552  0.23926358 -0.46081221 -0.21719304 -0.37980344
  -0.2038598 